adapters:
 - reverse-ws
enableVerify: false
verifyKey: 1234567890
debug: false
singleMode: false
cacheSize: 4096
adapterSettings:
  reverse-ws:
    ## 远端 websocket server 地址配置
    destinations:
    - host: chatgpt
      port: 8554
      path: /
      protocol: ws
